#!/usr/bin/env python3
"""
Local dimensional Model Maker.

Creates four distinct TRIDENT model artifacts from one recovered local architecture:
Movement, Evolution, Being, Design.

Input corpus is generated by the JS parent from the canonical Synthia DIMENSIONS object.
No network access is used or required.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import random
import sys
from pathlib import Path

import torch
import torch.nn as nn
from torch.optim import AdamW

ROOT = Path(__file__).resolve().parents[1]
VENDOR = ROOT / "vendor" / "trident"
sys.path.insert(0, str(VENDOR))

from model import Trident, TridentConfig  # noqa: E402

DIMENSIONS = ("Movement", "Evolution", "Being", "Design")


def sha256_file(path: Path) -> str:
    h = hashlib.sha256()
    with path.open("rb") as fh:
        for chunk in iter(lambda: fh.read(1024 * 1024), b""):
            h.update(chunk)
    return h.hexdigest()


def tokenize(text: str, vocab_size: int = 4096, max_len: int = 96) -> list[int]:
    ids = [ord(c) % vocab_size for c in text[:max_len]]
    if len(ids) < 2:
        ids = ids + [32, 32]
    return ids


def make_sequence(texts: list[str], cfg: TridentConfig) -> torch.Tensor:
    joined = "\n".join(texts)
    ids = tokenize(joined, cfg.vocab_size, min(cfg.max_seq_len, 192))
    return torch.tensor(ids, dtype=torch.long).unsqueeze(0)


def train_dimension(
    dimension: str,
    texts: list[str],
    out_path: Path,
    epochs: int,
    lr: float,
    seed: int,
) -> dict:
    random.seed(seed)
    torch.manual_seed(seed)

    cfg = TridentConfig()
    cfg.heads = [dimension]

    model = Trident(cfg)
    optimizer = AdamW(model.parameters(), lr=lr, weight_decay=1e-2)
    criterion = nn.CrossEntropyLoss()

    seq = make_sequence(texts, cfg)
    inp, tgt = seq[:, :-1], seq[:, 1:]

    losses = []
    model.train()
    for _ in range(max(1, epochs)):
        optimizer.zero_grad()
        logits = model(inp, head=dimension)
        loss = criterion(logits.reshape(-1, cfg.vocab_size), tgt.reshape(-1))
        loss.backward()
        nn.utils.clip_grad_norm_(model.parameters(), 1.0)
        optimizer.step()
        losses.append(float(loss.item()))

    torch.save(model.state_dict(), out_path)

    return {
        "dimension": dimension,
        "artifact": out_path.name,
        "sha256": sha256_file(out_path),
        "seed": seed,
        "epochs": max(1, epochs),
        "final_loss": losses[-1],
        "parameters": model.param_count(),
        "architecture": "TRIDENT single-specialist instance",
        "head": dimension,
    }


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--corpus", required=True)
    parser.add_argument("--out", required=True)
    parser.add_argument("--epochs", type=int, default=8)
    parser.add_argument("--lr", type=float, default=3e-4)
    parser.add_argument("--seed", type=int, default=1729)
    args = parser.parse_args()

    corpus_path = Path(args.corpus).resolve()
    out_dir = Path(args.out).resolve()
    out_dir.mkdir(parents=True, exist_ok=True)

    corpus = json.loads(corpus_path.read_text("utf-8"))
    if tuple(corpus.keys()) != DIMENSIONS:
        raise SystemExit(
            f"corpus must contain dimensions in exact order {DIMENSIONS}; got {tuple(corpus.keys())}"
        )

    models = []
    for index, dimension in enumerate(DIMENSIONS):
        texts = corpus.get(dimension)
        if not isinstance(texts, list) or not texts or not all(isinstance(x, str) and x.strip() for x in texts):
            raise SystemExit(f"{dimension} corpus is empty or invalid")
        artifact = out_dir / f"{dimension.lower()}.pt"
        models.append(
            train_dimension(
                dimension,
                texts,
                artifact,
                epochs=args.epochs,
                lr=args.lr,
                seed=args.seed + index,
            )
        )

    manifest = {
        "format": "synthia-dimensional-models-v1",
        "dimensions": list(DIMENSIONS),
        "model_source": "arrival-proof/vendor/trident/model.py",
        "model_source_sha256": sha256_file(VENDOR / "model.py"),
        "corpus_sha256": sha256_file(corpus_path),
        "models": models,
        "network_required": False,
    }
    manifest_path = out_dir / "manifest.json"
    manifest_path.write_text(json.dumps(manifest, indent=2), "utf-8")
    print(json.dumps({"ok": True, "manifest": str(manifest_path), "models": models}))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
